import voiceDetail from "./blitzit-detail.json";

export interface StoryChapter { heading: string; paragraphs: string[]; bullets?: string[] }
export interface StoryNarrative { opening: string[]; notes: Record<string, string[]>; chapters?: StoryChapter[]; closing: string[] }
export const narratives: Record<string, StoryNarrative> = {
  blitzit: {
    opening: [
      "A task app seems straightforward until the same task can be changed by a person, a connected service, and an AI assistant. Now a checkbox is part of a larger system. Who is allowed to change it? Which copy is current? What happens if the external service is down? Can the user undo what the assistant just did? These are the questions behind much of my work at Blitzit.",
      "I work on core backend and AI engineering. Over the last year, that has taken me from the existing app’s integrations and scheduling into the new platform, its shared tool layer, collaboration, migration, and most recently realtime voice. The visible feature changes, but the responsibility stays similar: connect a useful interaction to behavior the product can actually support.",
      "This story follows the work from connected tools to a voice assistant that can use them. The voice backend is merged; the complete frontend voice experience is in review as of October 2026."
    ],
    notes: {
      integrations: ["An integration is easy to underestimate if you only look at its happy path. Fetching a task is not the same problem as keeping it correct after a rename, a revoked grant, a partial outage, or a change that comes back through a webhook. A shared provider contract gave me one place to define what a provider supports, while leaving its actual mapping and API behavior explicit.","I did not want each integration to become a small backend of its own. The point of shared infrastructure was to keep ordinary concerns such as retries, ownership, and authentication consistent. It also made differences easier to see. A calendar event and a task are not interchangeable just because both have a title and a date."],
      "shared-tools": ["Tool count is useful as a measure of scope, but the more important decision was avoiding two sources of truth. If a tool is available to the in-app assistant and an external client, both should encounter the same validation and ownership checks. Maintaining parallel handlers would make it too easy for one surface to gain a capability without gaining the matching restriction.","The tool schema is only one part of that boundary. The executor still has to enforce it when a call arrives. That is especially important for read-only requests. Telling a model not to write is an instruction; preventing a write in the execution path is an actual product rule."],
      undo: ["Undo changes the relationship between a person and an assistant. Without it, a direct AI action can feel like handing over control. With it, the person can inspect a result and recover from a mistake. But a useful undo system has to know which state it is restoring and whether something has changed since the original action.","That is why I approached the journal as a sequence of changes rather than a second set of CRUD buttons. Content checks matter because the user may have edited the same task after the assistant did. A blind restore could turn the recovery feature into another source of data loss. A conflict should be visible, not quietly resolved by deleting somebody’s newer work."],
      collaboration: ["Realtime delivery and durable state have different jobs. A live event makes another person’s edit appear quickly. It should not be the only record that the edit happened. Keeping durable writes in the API and supporting recovery for clients makes the system less dependent on a perfect connection.","The same distinction showed up in database work. A long-lived change stream can consume a connection for a very different amount of time than an ordinary query. Sharing cursors and separating connection pressure helps keep those two workloads from competing in ways that are hard to understand from the interface alone."],
      memory: ["Remembered facts and inferred patterns should not be mixed without thought. A fact the user explicitly asks the assistant to remember has a different meaning from a pattern derived from activity. I kept those responsibilities separate so that the system could decide what to include, what to age out, and what to forget.","More context is not automatically better context. It adds cost, can crowd out the current task, and can make an old preference look more certain than it is. Budgets, attribution, deduplication, and user controls are part of making memory useful rather than simply making it large."],
      platform: ["The move from client-owned scheduling to server-owned scheduling was part of a broader change in responsibility. A recurring task should not depend on a particular client being awake at the right moment. Timezones, reminders, and retries belong in systems that can keep their own state and explain what they have done.","Billing has similarly specific boundaries. Managed-team billing does not mean every member shares the same workspace or data. Those are different product concepts, and the implementation has to preserve that difference. I try to be precise about those distinctions in both the code and the way I describe the work."],
      migration: ["A rewrite is much easier when you pretend the existing product is empty. A real migration starts with people who already have lists, recurring work, and their own expectations. Imports need to be safe to resume. Running them again should not duplicate the user’s work, and a later sync should not overwrite an edit made on the new platform.","I treated the old platform as a source to read from, then put safeguards around how that data entered the new one. Recurring templates needed separate treatment from occurrences that had already been generated. These are small distinctions on paper, but they decide whether the new app feels like a continuation or a reset."],
      reliability: ["Retries are not a substitute for understanding the failure. Retrying a revoked credential does not repair it. Retrying a throttled request immediately can make the problem worse. A provider timeout, an absent resource, and a permission failure need different handling, even if they all interrupt the same action on screen.","The useful engineering work is often making those differences survive the trip from provider response to queue decision to user-facing status. That makes incidents easier to investigate and gives the person using the product a next step they can actually take."]
    },
    chapters: voiceDetail,
    closing: ["The common thread is control. A person should know when Blitzy is listening, whether an action actually ran, what changed, and how to recover. That requires work across model boundaries, APIs, permissions, persistence, and the interface. None of those layers can provide the whole experience on its own.","This is the kind of engineering I enjoy: a feature that looks simple enough to use immediately, backed by decisions that hold up when the interaction gets complicated. Voice is the newest example. The integration framework, change journal, collaboration, and migration work are the foundation that gives it something useful to do."]
  },
  maddycustom: {
    opening: [
      "When someone buys a custom vehicle wrap, the website is only the beginning of the order. A design needs to match the right vehicle or product variant. Payment needs to be understood. Someone needs the correct artwork for production. Stock has to be accounted for. The parcel has to reach the customer, and support needs to know what happened if it does not.",
      "I joined MaddyCustom as a co-founder and led the technical work. Harshit handled the business side. My responsibility grew across the storefront, backend, and a separate admin platform. The interesting part was connecting those surfaces so that a choice made by the customer still made sense to the person preparing the order.",
      "MaddyCustom reported 100K+ monthly users and approximately $62.4K USD in annual revenue. Supporting that business meant looking beyond conversion at checkout. The software also had to help a small team understand payments, prepare the right products, and follow an order through delivery."
    ],
    notes: {
      commerce: [
        "The catalogue needed more structure than a collection of product names and prices. A design could belong to a category, a more specific category, and a particular variant. Those relationships affected where it appeared, what a buyer could select, and which production file the team would need. I carried that structure into the database and the browsing experience instead of trying to repair it later in the order flow.",
        "The customer-facing app used Next.js, React, and Redux. Persisted state mattered because shopping is rarely one uninterrupted session. A buyer can inspect a design, change a variant, open the cart, leave, and return. Cart state, offer eligibility, and the selected product details need to agree when they do. A polished product page does not help much if the checkout forgets what the customer chose.",
        "Search had to work with how people describe products. The implementation combines text search, fuzzy matching, field weighting, and availability checks. I also built product recommendations and category-specific presentation. The goal was to help a buyer reach a suitable product without requiring them to understand the structure of our catalogue.",
        "Offers introduced another layer of rules. A discount can depend on cart value, quantity, earlier orders, or a particular bundle. Putting those conditions into a model made the behavior explicit and gave the admin side a way to manage it. It also kept pricing decisions closer to the backend that creates the order, where they can be checked again."
      ],
      payments: [
        "A payment integration is not finished when the success callback opens a confirmation screen. The backend has to establish what was paid, for which order, through which provider, and what should happen next. It also has to cope with a callback arriving again or reaching the server after the customer has closed the page.",
        "I implemented paths for Razorpay and PayU, including provider selection based on health signals. The selection code records the preferred provider, the recommendation, and the reason for that decision. That record is useful later: an operations issue is much easier to investigate when the order explains how it entered a particular payment path.",
        "Provider status is still only a signal. It cannot promise that a particular bank or payment attempt will work. I treated fallback as a recovery option rather than a guarantee. The important part was making the decision explicit and connecting successful verification to a guarded post-payment flow.",
        "Partial payments and split shipments made the accounting more interesting. An order can carry a paid portion and a remaining amount, while its fulfillment may be divided into linked orders. The admin view needs to aggregate those amounts correctly. I worked on those totals as well as the payment path, because an incorrect operations view can be just as costly as an incorrect checkout.",
        "The post-payment flow touches inventory, coupon usage, fulfillment, and notifications. Database transactions help with changes inside MongoDB; an external shipping or messaging request is a separate side effect. I handled those boundaries separately so that a repeat or a partial failure had a sensible outcome."
      ],
      operations: [
        "The admin application became the other half of the product. Customers saw designs and a checkout. The team saw orders, production downloads, stock, packaging, support questions, and shipment states. Those are different views of the same work, and each needed enough context to act without repeatedly asking another person what to do.",
        "Production downloads are a good example. A generic export of the order table would not solve the problem. The team needed the correct templates for the selected design and variant. I built design search, template handling, and download workflows that connected those files to what had actually been ordered. Later fixes around multiple templates, variant availability, and exact search were part of keeping that workflow usable.",
        "Inventory has a similar connection to real work. Available and reserved quantities are not the same thing. A cancellation and a delivered order should not trigger the same stock behavior. The shipping integration maps external delivery events into the order lifecycle so the internal view can stay useful as the parcel moves.",
        "I also built department and role access, review moderation, offer controls, packaging tools, and tax exports. These are not the most dramatic screens in a portfolio, but they reduce the number of manual checks a small team needs to make. Building them taught me to ask who will use the result on an ordinary busy day, not just whether the feature looks finished in a demo."
      ],
      analytics: [
        "A sales total tells you what happened. It does not explain where a customer stopped. I built a first-party event model that follows the steps between a visit, a product view, the cart, the order form, the payment stage, and purchase. Events and sessions carry the context needed to connect those steps.",
        "Deduplication matters because a page can retry, rerender, or send the same logical event more than once. Without it, a chart can look precise while counting the wrong thing. I used validated ingestion and event identifiers to make the recorded journey more useful, then built the admin views on top of it.",
        "The dashboard includes drop-offs, timing between steps, comparisons across periods, and customer journey views. I also worked on understanding which first-purchase categories led to repeat buyers. That connects catalogue decisions to customer behavior, rather than only comparing products by their immediate sales.",
        "Attribution was another part of the picture. UTM history and server-side conversion events helped connect acquisition to orders. Those signals still need careful interpretation; an attribution field is not proof that one campaign caused a purchase. The practical value is giving the team a consistent view to investigate and compare. Meta tracking was later disabled in the archived storefront, so I describe it here as implemented work, not a service that is still running there."
      ],
      assistant: [
        "The screenshot below starts with a simple request: a red car and a budget. The response is a gallery of real products, with images, prices, discounts, and links. I wanted the assistant to help someone make a choice inside the shopping experience, rather than send them back to search with a paragraph of generic advice.",
        "I used the OpenAI Agents SDK to separate routing from the work itself. A classifier returns a Zod-validated category and extracted intent. Product discovery goes to a data-query agent with typed tools. Returns, installation, and care questions go to document retrieval. Simpler questions can take a direct-answer path, and requests for help from a person can hand off to WhatsApp support.",
        "The product-search tool accepts a query, keywords, category, price range, sort order, and page. Its result carries catalogue data such as images, prices, availability, and product links. The interface can render those results as cards. That connection matters: a recommendation should lead to a product the customer can actually inspect.",
        "Follow-up requests need state too. When someone says show more, the assistant should continue the previous search with the same budget and filters. I carried pagination state and search context through the conversation, including the current page and whether more results exist. The client also handles common continuation requests without making the customer repeat everything.",
        "Order support uses a different tool that reads the order state, delivery estimate, tracking link, and progress steps. Policy answers use file search over the knowledge base. Keeping those sources separate helped avoid treating a product recommendation, an order status, and a return rule as the same kind of answer.",
        "Shopping questions do not all need the same answer path. Finding a product, checking an order, explaining a policy, and asking for a person are different jobs. I built an agent flow that classifies the request and routes it to a suitable path instead of asking one prompt to improvise everything.",
        "The data-query path can use product and order tools. Policy questions can use document retrieval. A direct-answer path handles simpler responses, and a handoff path can point the customer toward human support. MongoDB-backed sessions preserve the conversation, while bounded context and summarization keep the history from growing without limit.",
        "The useful part of an assistant like this is its connection to the product. A fluent answer is not enough if it cannot find the right catalogue item or if it invents an order status. That experience informed how I later thought about AI tools at Blitzit: model output and application authority should be separate responsibilities."
      ],
      ownership: [
        "Owning the platform also meant watching the less visible costs. Images, serverless database connections, catalogue generation, and repeated API work all affect the bill and the reliability of the app. I worked on caching, connection pools, image delivery, and deployment behavior as the product changed.",
        "The main domain eventually moved to Shopify. The business had reached a different point, where maintenance effort and infrastructure predictability carried more weight. Building the custom platform gave me a practical understanding of that tradeoff: flexibility is valuable, but someone has to keep every part working.",
        "The original Next.js storefront and admin platform are the work shown here. They connected the customer’s choices to the team’s daily operations, and gave me experience with the full lifecycle of a commerce product."
      ]
    },
    closing: ["MaddyCustom made engineering feel very concrete. A wrong quantity could affect production. An unclear payment state could become a support conversation. A useful admin screen could save the team from checking several systems manually. That feedback changed how I judge a feature.","I came away with experience across the full product loop: deciding what needs to exist, building the customer interaction, connecting the backend, and supporting the people who operate it. The strongest part of the work is not a particular framework. It is that those pieces were built to serve the same business."]
  },
};
